config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "missions#index"

  get 'signup' => 'users#signup',:as => 'signup'
  get "login" => "users#login", :as => "login"                                        
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"
  
  namespace :admin do
    resources :missions do
      collection do
        get :search 
      end
    get :m_users, on: :member
  	post :add_user_to , on: :member
    resources :rm_user, only: [:destroy], :controller => "missions", :action => "rm_user"
    end

    resources :users do
    	get :u_missions, on: :member
    	post :add_mission_to , on: :member 
    	resources :rm_mission, only: [:destroy], :controller => "users", :action => "rm_mission"
    end	
  end
end

app/models/admin/user.rb
class Admin::User < User
  def toggle_admin!
    self.admin = !self.admin
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	
	has_many :works 
	has_many :missions, through: :works
	
	validates :name, presence: true
	validates :email,  format: { with: /\A[^@]+@[^@]+\z/}, uniqueness: true

	private	
	def admin?
  		self.role == "admin"
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  load_and_authorize_resource
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.all.page(params[:page]).per(5)
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.fetch(:admin_user, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:edit, :update, :destroy, :add_user, :add_mission_to]
	before_action :chek_mission_state, only: [:add_mission_to]
	before_action :check_login, except: [:login, :login, :signup, :create_login_session, :create ]
	layout "login", only: [:login, :signup, :create_login_session]
	
	def  index	
		@user = @current_user
		#redirect_to :action => "edit", :id => @user.id
		#@users = User.all.page(params[:page]).per(5)
	end
	
	def signup
		@user=User.new
	end
	
	def login
	end
	
	def create_login_session
	user =User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
		  session[:user_id]=user.id
		  redirect_to root_path
		else
		  redirect_to :login, notice: "沒有找到您的資料喔"
		end
	end

	def logout
		session[:user_id]=nil
		redirect_to login_path
	end
	
	
	def create
		@user = User.new(user_params)
		if @user.save
			#成功
			redirect_to :login, notice: "新增人員成功"
		else
			#失敗
		render :signup, notice: "新增人員失敗"
		end
	end
	#U
	def edit
    end
	
	def update
      if @user.update(user_params)
        # 成功
        redirect_to users_path, notice: "人員更新成功!"
      else
        # 失敗
        render :edit
      end
    end
	#D
	def destroy
      @user.destroy if @user
      redirect_to users_path, notice: "人員資料已刪除!"
    end

	def add_user
		@user = User.all
		@user = User.find_by(id: params[:id])	
	end
	#list mission's user
	def u_missions
		@user = User.find_by(id: params[:id])
		@missions = @user.missions.all
	end
	
	def rm_mission
	  work = Work.find_by(mission_id: params[:id], user_id: params[:user_id])
	  work.destroy
      redirect_to missions_path, notice: "人員已刪除!"
	end
	
	def add_mission_to
		unless Work.exists?(mission_id: @mission_id , user_id: params[:id]) == true
			@user.missions << @mission
			redirect_to u_missions_user_path, notice: "新增任務成功"		
		else
			redirect_to u_missions_user_path, notice: "任務已存在"
		end
	end
	
	private
    def user_params
      params.require(:user).permit(:name, :email, :mission_ids, :user, :password)
    end
	
	def find_user
		@user = User.find_by(id: params[:id])
	end
	
	def chek_mission_state
		if params[:mission][:name].blank? 
			@mission = Mission.find_by(id: params[:user][:mission_ids])
			@mission_id = @mission.id
		elsif Mission.exists?(name: params[:mission][:name]) == true
			@mission = Mission.find_by("name = ?", params[:mission][:name])	
			@mission_id = @mission.id
		elsif Mission.exists?(name: params[:mission][:name]) == false
			redirect_to u_missions_user_path, notice: "此任務不存在"
		end
	end	
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name, label: '用戶名', error: '請輸入用戶名' %><br />
  <%= f.input :email, label: 'Email', error: '請輸入email' %><br />
  <%= f.input :password, lable: '密碼', error: ' 請輸入密碼' %><br />
  <%= f.input :password_confirmation, label: '確認密碼', error: '請確認密碼' %><br />
  <%= f.button  :submit, lable:  '送出' %>

<% end %>

app/views/users/edit.html.erb
  <h1><%= t("edit") + t("view.user") %></h1>

  <%= render "user_form", user: @user %>
  
  <br />
  <%= link_to t("to") + t("view.user") + t("list"), users_path %>

app/views/users/index.html.erb
<h1><%= t("view.user") + t("list") %></h1>

  <%= link_to t("add") + t("view.user"), signup_path %>

  <table>
    <thead>
      <tr>
        <td><%= t("name") %></td>
        <td><%= t("view.email") %></td>
        <td><%= t("view.root") %></td>
		<td><%= t("view.missions") %></td>
      </tr>
    </thead>
    <tbody>
      <% @user.each do |user| %>
      <tr>
	    <td><%= user.name %>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
		<td><%= link_to user.missions.size, u_missions_user_path(user), method: "get" %></td>
        <td>
          <%= link_to t("edit"), edit_user_path(user) %>
          <%= link_to t("delete"), user_path(user), method: "delete", data: { confirm: t("confirm_delete") } %>
        </td>		
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/login.html.erb
<%= form_tag "create_login_session" do %>
    <%= label_tag "信箱" %>
    <%= text_field_tag :email ,params[:email] %></br>
    <%= label_tag "密碼" %>
    <%= password_field_tag :password, params[:password] %></br>
    <%= submit_tag "登錄" %>
<% end %>
<%= link_to t("add") + t("view.user"), signup_path %>

app/views/users/new.html.erb
  <h1><%= t("add") + t("view.user") %></h1>

  <%= render "user_form", user: @user %>

  <br />
  <%= link_to t("to") + t("view.mission") + t("list"), users_path %>

app/views/users/signup.html.erb
<h1><%= t("add") + t("view.user") %></h1>

<%= render "user_form", user: @user %>

<br />
<%= link_to "Back", :back %>

app/views/users/u_missions.html.erb
<h1><%= @user.name + t("view.mission") + t("list") %></h1>

	<%= form_tag add_mission_to_user_path do %>
	
	<%= search_field(:mission, :name) %><%= t("or") %>
	
	<%= collection_select(:user, :mission_ids, Mission.all, :id, :name) %>
	
    <%= submit_tag "新增任務" %>
	
	<% end %>
	

  <table>
    <thead>
      <tr>
        <td><%= t("view.mission") + t("name") %></td>
        <td><%= t("view.type") %></td>
        <td><%= t("view.information") %></td>
        <td><%= t("view.state") %></td>
		<td><%= t("view.important_level") %></td>
		<td><%= t("view.end_day") %></td>
		<td><%= t("view.supervisor") %></td>
		<td><%= t("view.users") %></td>
      </tr>
    </thead>
    <tbody>
      <% @missions.each do |mission| %>
      <tr>
	    <td><%= mission.name %>
        <td><%= mission.kind %></td>
        <td><%= mission.content %></td>
        <td><%= mission.state %></td>
		<td><%= mission.level %></td>
		<td><%= mission.end_date %></td>
		<td><%= mission.supervisor %></td>
		<td><%= link_to mission.users.size, m_users_mission_path(mission), method: "get" %></td>
        <td>
		<%= link_to t("delete"), user_rm_mission_path(@user, mission), method: "delete", data: { confirm: t("confirm_delete") } %>
		</td>		
      </tr>
      <% end %>
    </tbody>
  </table>