config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "missions#index"

  get 'signup' => 'users#signup',:as => 'signup'
  get "login" => "users#login", :as => "login"                                        
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"
  
  namespace :admin do
    resources :missions do
      collection do
        get :search 
      end
    get :m_users, on: :member
  	post :add_user_to , on: :member
    resources :rm_user, only: [:destroy], :controller => "missions", :action => "rm_user"
    end

    resources :users do
    	get :u_missions, on: :member
    	post :add_mission_to , on: :member 
    	resources :rm_mission, only: [:destroy], :controller => "users", :action => "rm_mission"
    end	
  end
end

app/models/admin/mission.rb
class Admin::Mission < Mission
	
end

app/models/mission.rb
class Mission < ApplicationRecord
	has_many :works
	has_many :mission_tags, dependent: :destroy
	has_many :users, through: :works
	
	validates :name, :state, :level, :supervisor, presence: true
	validates :name, length: {maximum: 200}
	
	accepts_nested_attributes_for :mission_tags
end

app/controllers/admin/missions_controller.rb
class Admin::MissionsController < ApplicationController
  layout 'admin'
  load_and_authorize_resource :mission, :user
  before_action :set_admin_mission, only: [:show, :edit, :update, :destroy]

  # GET /admin/missions
  # GET /admin/missions.json
  def index
    @admin_missions = Admin::Mission.all
  end

  # GET /admin/missions/1
  # GET /admin/missions/1.json
  def show
  end

  # GET /admin/missions/new
  def new
    @admin_mission = Admin::Mission.new
  end

  # GET /admin/missions/1/edit
  def edit
  end

  # POST /admin/missions
  # POST /admin/missions.json
  def create
    @admin_mission = Admin::Mission.new(admin_mission_params)

    respond_to do |format|
      if @admin_mission.save
        format.html { redirect_to @admin_mission, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @admin_mission }
      else
        format.html { render :new }
        format.json { render json: @admin_mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/missions/1
  # PATCH/PUT /admin/missions/1.json
  def update
    respond_to do |format|
      if @admin_mission.update(admin_mission_params)
        format.html { redirect_to @admin_mission, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_mission }
      else
        format.html { render :edit }
        format.json { render json: @admin_mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/missions/1
  # DELETE /admin/missions/1.json
  def destroy
    @admin_mission.destroy
    respond_to do |format|
      format.html { redirect_to admin_missions_url, notice: 'Mission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_mission
      @admin_mission = Admin::Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_mission_params
      params.fetch(:admin_mission, {})
    end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
	load_and_authorize_resource

	before_action :check_login
	before_action :find_mission, only: [:edit, :update, :destroy, :m_users, :add_user_to]
	before_action :chek_user, only: [:add_user_to]
	before_action :validates_search_key, only: [:search]
	before_action :check_create_by, only: [:update, :destroy, :m_users, :rm_user, :add_user_to]

	def index 
		sort_by = (params[:order] == 'end_date') ? 'end_date' : 'created_at'
		@missions =Mission.where(create_by: @current_user.name).order(sort_by).page(params[:page]).per(5)
	end

 	def search
 		@missions = Mission.ransack( name_or_content_cont: @q, create_by_eq: @current_user.name ).result(distinct: true).page(params[:page]).per(5)
  	end

	def new
		@mission = Mission.new
		@mission.mission_tags.build
	end
	
	def create
		@mission = Mission.new(mission_params)
		@mission.mission_tags.build(mission_params[:mission_tags])
		@mission.create_by = @current_user.name

		if @mission.save 
			redirect_to missions_path, notice: "新增任務成功"
		else
			render :new
		end
	end
	
	def edit
			@mission.mission_tags.build
    end
	
	def update

	    if @mission.update(mission_params) #|| @mission.mission_tags.build(mission_params[:mission_tags])
	        redirect_to missions_path, notice: "任務更新成功!"
	    else
	        render :edit
	    end
    end

	def destroy
		if @mission.users.size >0
			redirect_to missions_path, notice: "任務尚有人員未刪除!"
		else	
    		@mission.destroy if @mission
      		redirect_to missions_path, notice: "任務資料已刪除!"
      	end
    end
	
	def m_users #該任務所有處理人員
		@users = @mission.users.all
		#@now_mission = Mission.find(params[:id])
	end
	
	def rm_user 
	  #work = Work.find_by(mission_id: params[:mission_id], user_id: params[:id])
	  #work.destroy
	  user = User.find_by(id: params[:id])
	  mission = Mission.find_by(id: params[:mission_id])
	  mission.users.destroy(user)
	  redirect_to missions_path, notice: "人員已移除!"
	end
	
	def add_user_to
		unless Work.exists?(mission_id: params[:id], user_id: @user_id) == true
			@mission.users << @user
			redirect_to m_users_mission_path, notice: "新增人員成功"		
		else
			redirect_to m_users_mission_path, notice: "人員已存在"
		end
	end
	
private

    def mission_params
      params.require(:mission)
      	.permit(:name, :kind, :content, :state, :level, :end_date, :supervisor, :order,
      		mission_tags_attributes: [:tag1, :tag2, :tag3, :tag4, :tag5])
    end
	
	def find_mission
		@mission = Mission.find_by(id: params[:id])
	end
	
	def chek_user
		if params[:user][:name].blank? 
			@user = User.find_by(id: params[:mission][:user_ids])
			@user_id = @user.id
		elsif User.exists?(name: params[:user][:name]) == true
			@user = User.find_by("name = ?", params[:user][:name])	
			@user_id = @user.id
		elsif User.exists?(name: params[:user][:name]) == false
			redirect_to m_users_mission_path, notice: "此人員不存在"
		end
	end

	def check_create_by
		unless @mission.create_by == @current_user.name
			redirect_to missions_path, notice: "這並非您擁有的任務喔!"
		end		
	end

protected
 
	def validates_search_key
		if params[:query_string].blank?
			redirect_to missions_path
 		else
 			@q = params[:query_string].gsub(/\\|\'|\/|\?/, "") if params[:query_string].present?
 		end
 	end
end

app/helpers/admin/missions_helper.rb
module Admin::MissionsHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_index_form.html.erb
  <table class="table">
    <thead>
      <tr>
        <td><%= t("view.mission") + t("name") %></td>
        <td><%= t("view.type") %></td>
        <td><%= t("view.information") %></td>
        <td><%= t("view.state") %></td>
    		<td><%= t("view.important_level") %></td>
    		<td><%= link_to t("view.end_day"), missions_path(:order => 'end_date'), method: "get" %></td>
    		<td><%= t("view.supervisor") %></td>
    		<td><%= t("view.users") %></td>
        <td><%= "create_by" %></td>>
      </tr>
    </thead>
    <tbody>
      <% missions.each do |mission| %>
      <tr>
	     <td><%= mission.name %>
        <td><%= mission.kind %></td>
        <td><%= mission.content %></td>
        <td><%= mission.state %></td>
		    <td><%= mission.level %></td>
		    <td><%= mission.end_date %></td>
		    <td><%= mission.supervisor %></td>
		    <td><%= link_to mission.users.size, m_users_mission_path(mission), method: "get" %></td>
        <td><%= mission.create_by %></td>
        <td>
          <%= link_to t("edit"), edit_mission_path(mission), class:"btn btn-primary btn-xs" %>
          <%= link_to t("delete"), mission_path(mission), method: "delete", data: { confirm: t("confirm_delete") }, class:"btn btn-danger btn-xs" %>
        </td>		
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/missions/_mission_form.html.erb
  <%= simple_form_for(mission) do |f| %>

    <%= f.input :name, label: t("view.mission") + t("name"), error: '請輸入任務名稱' %>
    <%= f.input :kind, label: t("view.type") %>
    <%= f.input :content, label: t("view.information"), error: '請輸入內容' %>

	<%= f.label :state, t("view.state") %><br />
	<%= f.select(:state, [['待處理', 1], ['進行中', 2], ['已結束', 3]]) %><br />

	<%= f.label :level, t("view.important_level") %><br />
	<%= f.select(:level, [['首要', 1], ['優先', 2], ['可延宕', 3], ['無DL', 4]]) %><br />

	<%= f.input :end_date, as: :date, label: '結束日期' %>
	<%= f.input :supervisor, label: t("view.supervisor") %>
	<%= f.simple_fields_for :mission_tags do |m| %>
    	<%= m.input :tag1 %>
    	<%= m.input :tag2 %>
    	<%= m.input :tag3 %>
    	<%= m.input :tag4 %>
    	<%= m.input :tag5 %>
    <% end %>


	
	
    <%= f.submit %>
  <% end %>

app/views/missions/edit.html.erb
  <h1><%= t("edit")+t("view.mission") %></h1>

  <%= render "mission_form", mission: @mission %>

 
  <%= link_to t("to") + t("view.mission") + t("list"), missions_path %>

app/views/missions/index.html.erb
<h1><%= t("view.mission") + t("list") %></h1>
	<%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-TW" %>
	<%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>
	<%= Time.zone.now.to_date %>
	<%= link_to t("add")+t("view.mission"), new_mission_path %>
	<%= link_to t("view.user")+t("list"), users_path %>
  <%= form_tag search_missions_path, method: :get, class: 'questions-search-form'  do %>
    <div class="input-group input-group-lg">
      <input type="text" class="form-control" name="query_string" placeholder="關鍵字..">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-info btn-lg" >搜尋
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
  <% end %>

<%= render "index_form", missions: @missions %>

<%= paginate @missions %>

app/views/missions/m_users.html.erb
<h1><%= @mission.name + t("view.user") + t("list") %></h1>

  	<%= form_tag add_user_to_mission_path do %>
	
	<%= search_field(:user, :name) %><%= t("or") %>
	
	<%= collection_select(:mission, :user_ids, User.all, :id, :name) %>
	
    <%= submit_tag "新增人員" %>
	
	<% end %>

  <table>
    <thead>
      <tr>
        <td><%= t("name") %></td>
        <td><%= t("view.email") %></td>
        <td><%= t("view.root") %></td>
		<td><%= t("view.missions") %></td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
	    <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.root %></td>
		<td><%= link_to user.missions.size, u_missions_user_path(user), method: "get" %></td>
        <td>
        <%= link_to t("delete"), mission_rm_user_path(@mission, user), method: "delete", data: { confirm: t("confirm_delete") } %>
        </td>		
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/missions/new.html.erb
  <h1><%= t("add") + t("view.mission") %></h1>
  
  <%= render "mission_form", mission: @mission %>

  <br />
  <%= link_to t("to")+t("view.mission"), missions_path %>

app/views/missions/search.html.erb
<h1><%= t("view.mission") + t("list") %></h1>
	<%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-TW" %>
	<%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>
	<%= Time.zone.now.to_date %>
	<%= link_to t("add")+t("view.mission"), new_mission_path %>
	<%= link_to t("view.user")+t("list"), users_path %>
  <%= form_tag search_missions_path, method: :get, class: 'questions-search-form'  do %>
    <div class="input-group input-group-lg">
      <input type="text" class="form-control" name="query_string" placeholder="關鍵字..">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-danger" >搜尋
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
  <% end %>
<div class="form-group">
<%= render "index_form", missions: @missions %>
</div>
<%= paginate @missions %>